<template>
    <div>
        <div class="dheader_div">
            <img src="src/assets/images/返回.png" alt="" @click="back()">
            <span>商品详情</span>
        </div>
        <img :src="list[msg].src" alt="">

    </div>

</template>


<script>
    export default{
        data(){
            return{
                msg:0,

                list:[
                    {
                        src:'./src/assets/images/T11.png',
                        id:'0'
                    },
                    {
                        src:'./src/assets/images/T12.png',
                        id:'1'
                    },
                    {
                        src:'./src/assets/images/T13.png',
                        id:'2'
                    },
                    {
                        src:'./src/assets/images/T14.png',
                        id:'3'
                    },
                    {
                        src:'./src/assets/images/T15.png',
                        id:'4'
                    },
                    {
                        src:'./src/assets/images/T16.png',
                        id:'5'
                    },
                    {
                        src:'./src/assets/images/T17.png',
                        id:'6'
                    },
                    {
                        src:'./src/assets/images/T18.png',
                        id:'7'
                    },
                    {
                        src:'./src/assets/images/T19.png',
                        id:'8'
                    },
                    {
                        src:'./src/assets/images/T110.png',
                        id:'9'
                    },
                    {
                        src:'./src/assets/images/T111.png',
                        id:'10'
                    },
                    {
                        src:'./src/assets/images/T112.png',
                        id:'11'
                    },
                    {
                        src:'./src/assets/images/FX1.png',
                        id:'12'
                    },
                    {
                        src:'./src/assets/images/FX2.png',
                        id:'13'
                    },
                    {
                        src:'./src/assets/images/REXL1.png',
                        id:'14'
                    },
                    {
                        src:'./src/assets/images/REXL2.png',
                        id:'15'
                    },
                    {
                        src:'./src/assets/images/REXL3.png',
                        id:'16'
                    },
                    {
                        src:'./src/assets/images/REXL4.png',
                        id:'17'
                    },
                    {
                        src:'./src/assets/images/ZSPJ1.png',
                        id:'18'
                    },
                    {
                        src:'./src/assets/images/ZSPJ2.png',
                        id:'19'
                    },
                    {
                        src:'./src/assets/images/ZSPJ3.png',
                        id:'20'

                    },
                    {
                        src:'./src/assets/images/TH21.png',
                        id:'21'
                    },
                    {
                        src:'./src/assets/images/TH21.png',
                        id:'22'
                    },
                    {
                        src:'./src/assets/images/TH21.png',
                        id:'23'

                    },
                    {
                        src:'./src/assets/images/TH21.png',
                        id:'24'
                    },
                    {
                        src:'./src/assets/images/TH21.png',
                        id:'25'
                    },
                    {
                        src:'./src/assets/images/TH21.png',
                        id:'26'

                    },
                    {
                        src:'./src/assets/images/TH21.png',
                        id:'27'
                    },
                    {
                        src:'./src/assets/images/TH21.png',
                        id:'28'
                    },
                    {
                        src:'./src/assets/images/TH21.png',
                        id:'29'
                    },
                    {
                        src:'./src/assets/images/TH21.png',
                        id:'30'
                    },
                    {
                        src:'./src/assets/images/TH31.png',
                        id:'31'
                    },
                    {
                        src:'./src/assets/images/TH31.png',
                        id:'32'
                    },
                    {
                        src:'./src/assets/images/TH31.png',
                        id:'33'

                    },
                    {
                        src:'./src/assets/images/TH31.png',
                        id:'34'
                    },
                    {
                        src:'./src/assets/images/TH31.png',
                        id:'35'
                    },
                    {
                        src:'./src/assets/images/TH31.png',
                        id:'36'

                    },
                    {
                        src:'./src/assets/images/TH31.png',
                        id:'37'
                    },
                    {
                        src:'./src/assets/images/TH31.png',
                        id:'38'
                    },
                    {
                        src:'./src/assets/images/TH31.png',
                        id:'39'
                    },
                    {
                        src:'./src/assets/images/TH31.png',
                        id:'40'
                    },
                    {
                        src:'./src/assets/images/TH41.png',
                        id:'41'
                    },
                    {
                        src:'./src/assets/images/TH41.png',
                        id:'42'
                    },
                    {
                        src:'./src/assets/images/TH41.png',
                        id:'43'

                    },
                    {
                        src:'./src/assets/images/TH41.png',
                        id:'44'
                    },
                    {
                        src:'./src/assets/images/TH41.png',
                        id:'45'
                    },
                    {
                        src:'./src/assets/images/TH41.png',
                        id:'46'

                    },
                    {
                        src:'./src/assets/images/TH41.png',
                        id:'47'
                    },
                    {
                        src:'./src/assets/images/TH41.png',
                        id:'48'
                    },
                    {
                        src:'./src/assets/images/TH41.png',
                        id:'49'
                    },
                    {
                        src:'./src/assets/images/TH41.png',
                        id:'50'
                    },
                    {
                        src:'./src/assets/images/TH51.png',
                        id:'51'
                    },
                    {
                        src:'./src/assets/images/TH51.png',
                        id:'52'
                    },
                    {
                        src:'./src/assets/images/TH51.png',
                        id:'53'

                    },
                    {
                        src:'./src/assets/images/TH51.png',
                        id:'54'
                    },
                    {
                        src:'./src/assets/images/TH51.png',
                        id:'55'
                    },
                    {
                        src:'./src/assets/images/TH51.png',
                        id:'56'

                    },
                    {
                        src:'./src/assets/images/TH51.png',
                        id:'57'
                    },
                    {
                        src:'./src/assets/images/TH51.png',
                    },
                    {
                        src:'./src/assets/images/TH51.png',
                        id:'59'
                    },
                    {
                        src:'./src/assets/images/TH51.png',
                        id:'60'
                    },
                    {
                        src:'./src/assets/images/TH181.png',
                        id:'61'
                    },
                    {
                        src:'./src/assets/images/TH181.png',
                        id:'62'
                        
                    },
                    {
                        src:'./src/assets/images/TH181.png',
                        id:'63'


                    },
                    {
                        src:'./src/assets/images/TH181.png',
                        id:'64'
                    },
                    {
                        src:'./src/assets/images/TH181.png',
                        id:'65'
                    },
                    {
                        src:'./src/assets/images/TH181.png',
                        id:'66'

                    },
                    {
                        src:'./src/assets/images/TH181.png',
                        id:'67'
                    },
                    {
                        src:'./src/assets/images/TH181.png',
                        id:'68'
                    },
                    {
                        src:'./src/assets/images/TH181.png',
                        id:'69'
                    },
                    {
                        src:'./src/assets/images/TH181.png',
                        id:'70'
                    },
                    {
                        src:'./src/assets/images/TH171.png',
                        id:'71'
                    },
                    {
                        src:'./src/assets/images/TH171.png',
                        id:'72'
                    },
                    {
                        src:'./src/assets/images/TH171.png',
                        id:'73'

                    },
                    {
                        src:'./src/assets/images/TH171.png',
                        id:'74'
                    },
                    {
                        src:'./src/assets/images/TH171.png',
                        id:'75'
                    },
                    {
                        src:'./src/assets/images/TH171.png',
                        id:'76'

                    },
                    {
                        src:'./src/assets/images/TH171.png',
                        id:'77'
                    },
                    {
                        src:'./src/assets/images/TH171.png',
                        id:'78'
                    },
                    {
                        src:'./src/assets/images/TH171.png',
                        id:'79'
                    },
                    {
                       src:'./src/assets/images/TH171.png',
                        id:'80'
                    },
                    {
                        src:'./src/assets/images/TH161.png',
                        id:'81'
                    },
                    {
                        src:'./src/assets/images/TH161.png',
                        id:'82'
                    },
                    {
                        src:'./src/assets/images/TH161.png',
                        id:'83'

                    },
                    {
                        src:'./src/assets/images/TH161.png',
                        id:'84'
                    },
                    {
                        src:'./src/assets/images/TH161.png',
                        id:'85'
                    },
                    {
                        src:'./src/assets/images/TH161.png',
                        id:'86'

                    },
                    {
                        src:'./src/assets/images/TH161.png',
                        id:'87'
                    },
                    {
                        src:'./src/assets/images/TH161.png',
                        id:'88'
                    },
                    {
                        src:'./src/assets/images/TH161.png',
                        id:'89'
                    },
                    {
                       src:'./src/assets/images/TH161.png',
                        id:'90'
                    },
                    {
                        src:'./src/assets/images/TH151.png',
                        id:'91'
                    },
                    {
                        src:'./src/assets/images/TH151.png',
                        id:'92'
                    },
                    {
                        src:'./src/assets/images/TH151.png',
                        id:'93'

                    },
                    {
                        src:'./src/assets/images/TH151.png',
                        id:'94'
                    },
                    {
                        src:'./src/assets/images/TH151.png',
                        id:'95'
                    },
                    {
                        src:'./src/assets/images/TH151.png',
                        id:'96'

                    },
                    {
                        src:'./src/assets/images/TH151.png',
                        id:'97'
                    },
                    {
                        src:'./src/assets/images/TH151.png',
                        id:'98'
                    },
                    {
                        src:'./src/assets/images/TH151.png',
                        id:'99'
                    },
                    {
                       src:'./src/assets/images/TH151.png',
                        id:'100'
                    },
                    {
                        src:'./src/assets/images/TH141.png',
                        id:'101'
                    },
                    {
                        src:'./src/assets/images/TH141.png',
                        id:'102'
                    },
                    {
                        src:'./src/assets/images/TH141.png',
                        id:'103'

                    },
                    {
                        src:'./src/assets/images/TH141.png',
                        id:'104'
                    },
                    {
                        src:'./src/assets/images/TH141.png',
                        id:'105'
                    },
                    {
                        src:'./src/assets/images/TH141.png',
                        id:'106'

                    },
                    {
                        src:'./src/assets/images/TH141.png',
                        id:'107'
                    },
                    {
                        src:'./src/assets/images/TH141.png',
                        id:'108'
                    },
                    {
                        src:'./src/assets/images/TH141.png',
                        id:'109'
                    },
                    {
                       src:'./src/assets/images/TH141.png',
                        id:'110'
                    },
                    {
                        src:'./src/assets/images/TH91.png',
                        id:'111'
                    },
                    {
                        src:'./src/assets/images/TH91.png',
                        id:'112'
                    },
                    {
                        src:'./src/assets/images/TH91.png',
                        id:'113'

                    },
                    {
                        src:'./src/assets/images/TH91.png',
                        id:'114'
                    },
                    {
                       src:'./src/assets/images/TH91.png',
                        id:'115'
                    },
                    {
                       src:'./src/assets/images/TH91.png',
                        id:'116'

                    },
                    {
                        src:'./src/assets/images/TH91.png',
                        id:'117'
                    },
                    {
                        src:'./src/assets/images/TH91.png',
                        id:'118'
                    },
                    {
                        src:'./src/assets/images/TH91.png',
                        id:'119'
                    },
                    {
                       src:'./src/assets/images/TH91.png',
                        id:'120'
                    },
                ],
            }
        },
        mounted(){
            console.log(this.$route.params.id)
            this.msg=this.$route.params.id
        },
        methods:{
            back(){
                this.$router.go(-1)
            }
        }
    }

</script>

<style>
    .dheader_div{
        height: 30px;
        align-items: center;
        display: flex;
        padding-top: 10px;
    }
    .dheader_div img{
        width: 7%;
        margin-left: 5%;
    }
    .dheader_div span{
        margin-left: 5%;
    }
</style>